# Site settings
title: Simplicity
email: durandj@noreply.github.com
description: > # this means to ignore newlines until "baseurl:"
  Simplicity is a simple Window Manager that is heavily inspired by
  the Awesome window manager. I liked the idea but wanted something
  just slightly different.
baseurl: "/simplicity" # the subpath of your site, e.g. /blog/
url: "http://durandj.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  durandj

# Build settings
markdown: kramdown
